/// <reference types="node" />
// Node types for this file only: the app itself runs in the browser.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { COLOURS, PUBLIC_FILES, manifestJson, renderHead } from "../../../scripts/brand-meta.mjs";

/* ============================================================================
   The brand kit lands where a custom property cannot be read: the manifest is
   read by the OS, theme-color by the browser chrome, the favicon and the
   social card by crawlers. The head and the manifest are generated from
   scripts/brand-meta.mjs at build; the SVGs and PNGs are generated by
   scripts/brand-draw.mjs and scripts/brand-assets.mjs and committed. This file
   holds each of those outputs to the token it came from and to the rules in
   brand/BRAND.md, so a change that is not carried through fails here.
   ========================================================================== */

const repo = (path: string) => fileURLToPath(new URL(`../../../${path}`, import.meta.url));
const text = (path: string) => readFileSync(repo(path), "utf8");

// Read independently of brand-meta.mjs, so a wrong token there is caught too.
const tokens = JSON.parse(text("packages/tokens/src/tokens.json"));
const hex = (v: string) => v.toUpperCase();
const VOID = hex(tokens.primitive.colour.void.$value);
const PHOSPHOR = hex(tokens.primitive.colour.phosphor.$value);
const ACID = hex(tokens.primitive.colour.acid.$value);
const GREY_400 = hex(tokens.primitive.ramp["grey-400"].$value);
const GREY_500 = hex(tokens.primitive.ramp["grey-500"].$value);

const html = text("apps/showcase/index.html");
const head = renderHead(html, { base: "/" }).replace(/\s+/g, " ");
const manifest = JSON.parse(manifestJson());

function meta(attr: "name" | "property", key: string): string | undefined {
  return head.match(new RegExp(`<meta ${attr}="${key}" content="([^"]*)"`))?.[1];
}

describe("brand metadata", () => {
  it("fills every placeholder in index.html", () => {
    expect(head).not.toMatch(/%NX_[A-Z_]+%/);
  });

  it("links the manifest under the deployed base, which Vite cannot add for it", () => {
    // The manifest is emitted by the build, not copied from public/, so Vite
    // leaves its link alone. On Pages an unprefixed link is a 404.
    expect(renderHead(html, { base: "/nexus/" })).toContain(
      '<link rel="manifest" href="/nexus/site.webmanifest" />',
    );
  });

  it("takes theme-color and both manifest colours from the page ground", () => {
    expect(COLOURS.ground.toUpperCase()).toBe(VOID);
    expect(meta("name", "theme-color")?.toUpperCase()).toBe(VOID);
    expect(manifest.theme_color.toUpperCase()).toBe(VOID);
    expect(manifest.background_color.toUpperCase()).toBe(VOID);
  });

  it("gives crawlers absolute https URLs, since they reject relative ones", () => {
    for (const [attr, key] of [
      ["property", "og:image"],
      ["property", "og:url"],
      ["name", "twitter:image"],
    ] as const) {
      expect(meta(attr, key), key).toMatch(/^https:\/\//);
    }
    expect(head).toMatch(/<link rel="canonical" href="https:\/\//);
  });
});

describe("brand assets", () => {
  // Every colour each shipped source may use, by BRAND.md's Mark rules: the
  // mark is phosphor on void and nothing else; acid appears only as signal on
  // the cards; alarm appears nowhere. The refused candidates in
  // brand/assets/logo/ are a record and are not held to this.
  const ALLOWED: Record<string, string[]> = {
    "logo/mark.svg": [VOID, PHOSPHOR],
    "logo/mark-mono.svg": ["currentColor"],
    "logo/mark-inverted.svg": [VOID],
    "logo/favicon.svg": [VOID, PHOSPHOR],
    "logo/icon-maskable.svg": [VOID, PHOSPHOR],
    "logo/wordmark.svg": [PHOSPHOR],
    "social/social-card.svg": [VOID, PHOSPHOR, ACID, GREY_400, GREY_500],
    "social/github-card.svg": [VOID, PHOSPHOR, ACID, GREY_400, GREY_500],
    "readme-header.svg": [VOID, PHOSPHOR, ACID, GREY_400],
  };

  it.each(Object.entries(ALLOWED))("%s uses only its allowed colours", (file, allowed) => {
    const svg = text(`brand/assets/${file}`);
    const paints = Array.from(
      svg.matchAll(/\b(?:fill|stroke|stop-color|color)\s*[=:]\s*"?([^";>]+)/g),
      (m) => m[1].trim(),
    ).filter((v) => v !== "none" && !v.startsWith("url(#"));
    expect(paints.length, "no paints found — has the drawing changed shape?").toBeGreaterThan(0);
    for (const paint of paints) {
      const value = /^#[0-9a-f]{6}$/i.test(paint) ? hex(paint) : paint;
      expect(allowed, `${paint} in ${file}`).toContain(value);
    }
  });

  it.each(PUBLIC_FILES)("serves brand/assets/%s unchanged as public/%s", (from, to) => {
    const a = readFileSync(repo(`brand/assets/${from}`));
    const b = readFileSync(repo(`apps/showcase/public/${to}`));
    expect(b.equals(a), "run node scripts/brand-assets.mjs").toBe(true);
  });
});
