// Compile-time constants injected by vite.config.ts `define`, sourced from
// scripts/ds-figures.mjs. Declared here so tsc knows about them.
declare const __NX_VERSION__: string;
declare const __NX_TOKENS__: number;
declare const __NX_COMPONENTS__: number;
// The Home page title, from scripts/brand-meta.mjs: the same string as the
// static <title> crawlers read, so the tab does not change on mount.
declare const __NX_TITLE__: string;

// The component token layer, generated by scripts/component-layer.mjs through
// the nx-component-layer plugin in vite.config.ts.
declare module "virtual:nx-component-layer" {
  const layer: {
    hooks: Array<[string, Array<{ name: string; fallback: string }>]>;
    usedBy: Array<[string, string[]]>;
  };
  export default layer;
}
