#!/usr/bin/env node
// Regenerates the library-code + CSS portion of reference/preview.jsx from
// the real source in packages/react/src and packages/tokens/src, so the
// file's own header comment ("this preview cannot drift from the packages")
// is actually true instead of aspirational.
//
// The PAGES/SHELL section below the generated boundary is a deliberate,
// separate demo — it mirrors apps/showcase/src/pages/*.tsx, it is not a
// literal copy of it — and is left untouched by this script.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { esbuildAlias } from "../workspace-alias.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const previewPath = join(root, "reference/preview.jsx");
const BOUNDARY = "PAGES — mirrors apps/showcase/src/pages";

async function main() {
  const existing = readFileSync(previewPath, "utf8");
  const boundaryLineStart = existing.lastIndexOf("/* ====", existing.indexOf(BOUNDARY));
  if (boundaryLineStart < 0) {
    throw new Error(
      "Could not find the PAGES boundary comment in reference/preview.jsx — " +
      "has the hand-authored section been renamed or removed?",
    );
  }
  const tail = existing.slice(boundaryLineStart);

  const result = await build({
    entryPoints: [join(root, "packages/react/src/index.ts")],
    bundle: true,
    write: false,
    format: "esm",
    jsx: "transform", // classic React.createElement output — no jsx-runtime import needed standalone
    // The source packages set "jsx": "react-jsx" in their own tsconfig.json,
    // which esbuild's TS handling treats as authoritative over the `jsx`
    // build option above — passing tsconfigRaw bypasses that file-based
    // discovery for this one build so the classic transform actually applies.
    tsconfigRaw: { compilerOptions: { jsx: "react" } },
    external: ["react"],
    // Without this, "@nexus/tokens" resolves through packages/tokens'
    // package.json `exports`, which points at dist/ — so this script would
    // depend on packages/tokens having been rebuilt first, and would
    // silently bundle stale dist/ output otherwise. That is exactly the
    // scenario CI's own drift-check error message invites: it tells a
    // developer to run `npm run build:preview` after editing source, with no
    // mention of rebuilding tokens first.
    alias: esbuildAlias,
    target: "es2020",
    legalComments: "none",
  });
  const libraryJs = result.outputFiles[0].text.trim();

  const css = [
    readFileSync(join(root, "packages/tokens/src/tokens.css"), "utf8"),
    readFileSync(join(root, "packages/tokens/src/crt.css"), "utf8"),
    readFileSync(join(root, "packages/react/src/styles.css"), "utf8"),
  ]
    .join("\n")
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");

  const header = `/* ============================================================================
   Nexus Cyberdeck — single-file preview of the design system.

   The library code below is the REAL @nexus/react source, bundled by esbuild
   straight from packages/react/src with types stripped. The CSS is the real
   tokens.css + crt.css + styles.css concatenated. Nothing here is a
   re-implementation, so this preview cannot drift from the packages — this
   file is regenerated by \`npm run build:preview\` (scripts/build-preview.mjs),
   not hand-edited. CI re-runs it and fails on any diff.

   In a real install you would instead:
     import "@nexus/tokens/tokens.css";
     import { Panel, Drawer } from "@nexus/react";
   ========================================================================== */

${libraryJs}

const NX_CSS = \`${css}\`;

`;

  writeFileSync(previewPath, header + tail);
  console.log("reference/preview.jsx regenerated from packages/react/src and packages/tokens/src.");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
