#!/usr/bin/env node
// Fails when a figure quoted in prose drifts from the code.
//
// The showcase reads its figures at build time (apps/showcase/vite.config.ts
// `define`) and scripts/build-preview.mjs stamps them into
// reference/preview.jsx, so neither of those can be stale for long. Prose
// cannot be generated, and prose is where a number rots quietly: a README
// still advertising nineteen components a year after the twentieth landed.
//
// Two rules make this worth running:
//
//   1. EVERY occurrence of a figure in a checked file is compared, not the
//      first one. Three lines of README.md quote the component count.
//   2. A pattern that matches NOTHING is a failure, not a pass. The previous
//      version guarded each check with `if (match && match !== expected)`, so
//      a regex that stopped matching — because a line was reflowed, a section
//      rewritten, or a table replaced a list — was indistinguishable from a
//      passing check. It would have printed "Docs OK" forever with nothing
//      left to assert.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { componentCount, shortVersion, tokenCount, version } from "./ds-figures.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const read = (p) => readFileSync(join(root, p), "utf8");

/**
 * Every file that quotes a figure in prose, and what it must say. Adding a
 * doc that names a count means adding a line here; forgetting to is the one
 * failure mode this file cannot catch itself.
 */
const CHECKS = [
  {
    file: "README.md",
    pattern: /(\d+) components/g,
    expected: componentCount,
    what: "the component count",
  },
  { file: "README.md", pattern: /(\d+) tokens/g, expected: tokenCount, what: "the token count" },
  {
    file: "packages/react/README.md",
    pattern: /(\d+) components/g,
    expected: componentCount,
    what: "the component count",
  },
  // Generated, but generated by a regex stamp that silently does nothing when
  // it fails to match — so it is checked here as well as by CI's drift gate.
  {
    file: "reference/preview.jsx",
    pattern: /(\d+) tokens ·/g,
    expected: tokenCount,
    what: "the token count",
  },
  {
    file: "reference/preview.jsx",
    pattern: /· (\d+) components/g,
    expected: componentCount,
    what: "the component count",
  },
  {
    file: "reference/preview.jsx",
    pattern: /DS v(\d+\.\d+)/g,
    expected: shortVersion,
    what: "the version",
  },
];

const problems = [];

for (const { file, pattern, expected, what } of CHECKS) {
  const found = [...read(file).matchAll(pattern)];
  if (found.length === 0) {
    problems.push(
      `${file} no longer quotes ${what} anywhere — this check has gone silent. ` +
        `Restore the figure, or remove the assertion from scripts/check-docs.mjs deliberately.`,
    );
    continue;
  }
  for (const match of found) {
    if (match[1] !== String(expected)) {
      problems.push(
        `${file} advertises "${match[0].trim()}" — the code has ${expected} for ${what}`,
      );
    }
  }
}

if (problems.length) {
  console.error("Documentation disagrees with the code:\n");
  for (const p of problems) console.error(`  • ${p}`);
  console.error("");
  process.exit(1);
}

console.log(
  `Docs OK — DS v${shortVersion} (${version}), ${tokenCount} tokens · ${componentCount} components, ` +
    `${CHECKS.length} assertions.`,
);
