#!/usr/bin/env node
// Fails when a figure quoted in prose drifts from the code.
//
// The showcase reads its figures at build time (apps/showcase/vite.config.ts
// `define`) and scripts/build-preview.mjs stamps them into
// reference/preview.jsx, so neither of those can be stale for long. Prose
// cannot be generated, and prose is where a number rots quietly: a README
// still advertising nineteen components a year after the twentieth landed.
//
// Two rules make this worth running:
//
//   1. EVERY occurrence of a figure in a checked file is compared, not the
//      first one. Three lines of README.md quote the component count.
//   2. A pattern that matches NOTHING is a failure, not a pass. The previous
//      version guarded each check with `if (match && match !== expected)`, so
//      a regex that stopped matching — because a line was reflowed, a section
//      rewritten, or a table replaced a list — was indistinguishable from a
//      passing check. It would have printed "Docs OK" forever with nothing
//      left to assert.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { componentCount, shortVersion, tokenCount, version } from "./ds-figures.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const read = (p) => readFileSync(join(root, p), "utf8");

/**
 * A ratio out of the generated contrast table, formatted the way prose quotes
 * it. Both READMEs advertise the two ramp steps the AA claim rests on, and
 * those are hand-typed numbers about accessibility — exactly the kind this
 * file exists to stop from rotting. The token build already fails when a step
 * drops under its *floor*; this catches the other half, a step that moves
 * within the floor and leaves the README quoting the old figure.
 */
const contrast = read("packages/tokens/src/contrast.gen.ts");
function ratio(theme, step) {
  const block = contrast.match(new RegExp(`"${theme}": \\{([\\s\\S]*?)\\n  \\}`));
  const found = block?.[1].match(new RegExp(`"${step}": ([\\d.]+),`));
  if (!found) {
    throw new Error(
      `contrast.gen.ts has no ${theme}/${step} entry — regenerate it with ` +
        `\`npm run build:tokens\`, or update scripts/check-docs.mjs deliberately.`,
    );
  }
  return Number(found[1]).toFixed(2);
}

/**
 * Every file that quotes a figure in prose, and what it must say. Adding a
 * doc that names a count means adding a line here; forgetting to is the one
 * failure mode this file cannot catch itself.
 *
 * A check with one figure names it in `expected`/`what`. A check whose pattern
 * spans several cells of a table row lists one `{ expected, what }` per capture
 * group in `captures`, in order, so every column is held to the code and not
 * only the first: the `hud` column of both theme tables quoted grey-100 (the
 * decorative hairline) as the UI boundary for as long as only the `hud-aa`
 * column was asserted.
 */
const CHECKS = [
  {
    file: "README.md",
    pattern: /(\d+) components/g,
    expected: componentCount,
    what: "the component count",
  },
  { file: "README.md", pattern: /(\d+) tokens/g, expected: tokenCount, what: "the token count" },
  {
    file: "packages/react/README.md",
    pattern: /(\d+) components/g,
    expected: componentCount,
    what: "the component count",
  },
  // Generated, but generated by a regex stamp that silently does nothing when
  // it fails to match — so it is checked here as well as by CI's drift gate.
  {
    file: "reference/preview.jsx",
    pattern: /(\d+) tokens ·/g,
    expected: tokenCount,
    what: "the token count",
  },
  {
    file: "reference/preview.jsx",
    pattern: /· (\d+) components/g,
    expected: componentCount,
    what: "the component count",
  },
  {
    file: "reference/preview.jsx",
    pattern: /DS v(\d+\.\d+)/g,
    expected: shortVersion,
    what: "the version",
  },
  // Both theme tables: first column hud-aa, second column hud. Disabled text
  // is grey-300 (semantic.fg.disabled); the UI boundary is grey-200
  // (semantic.border.strong), not the grey-100 hairline.
  {
    file: "README.md",
    pattern: /\| disabled text\s+\| (\d+\.\d+):1\s+\| (\d+\.\d+):1/g,
    captures: [
      { expected: ratio("hud-aa", "grey-300"), what: "hud-aa disabled-text contrast" },
      { expected: ratio("hud", "grey-300"), what: "hud disabled-text contrast" },
    ],
  },
  {
    file: "README.md",
    pattern: /\| UI boundaries\s+\| (\d+\.\d+):1\s+\| (\d+\.\d+):1/g,
    captures: [
      { expected: ratio("hud-aa", "grey-200"), what: "hud-aa UI-boundary contrast" },
      { expected: ratio("hud", "grey-200"), what: "hud UI-boundary contrast" },
    ],
  },
  {
    file: "packages/tokens/README.md",
    pattern: /\| Disabled text contrast\s+\| (\d+\.\d+):1\s+\| (\d+\.\d+):1/g,
    captures: [
      { expected: ratio("hud-aa", "grey-300"), what: "hud-aa disabled-text contrast" },
      { expected: ratio("hud", "grey-300"), what: "hud disabled-text contrast" },
    ],
  },
  {
    file: "packages/tokens/README.md",
    pattern: /\| UI boundary contrast\s+\| (\d+\.\d+):1\s+\| (\d+\.\d+):1/g,
    captures: [
      { expected: ratio("hud-aa", "grey-200"), what: "hud-aa UI-boundary contrast" },
      { expected: ratio("hud", "grey-200"), what: "hud UI-boundary contrast" },
    ],
  },
  // The preview's hand-authored tail (below the PAGES boundary, which
  // build-preview.mjs copies verbatim) quotes the same hud boundary figure in
  // its muted-ramp a11y note. Slider tracks use --nx-border-strong, grey-200.
  {
    file: "reference/preview.jsx",
    pattern: /border token used for slider tracks sits at (\d+\.\d+):1/g,
    expected: ratio("hud", "grey-200"),
    what: "hud slider-track (UI-boundary) contrast",
  },
];

const problems = [];
let assertions = 0;

for (const check of CHECKS) {
  const { file, pattern } = check;
  const captures = check.captures ?? [{ expected: check.expected, what: check.what }];
  assertions += captures.length;
  const found = [...read(file).matchAll(pattern)];
  if (found.length === 0) {
    problems.push(
      `${file} no longer quotes ${captures.map((c) => c.what).join(" / ")} anywhere — this ` +
        `check has gone silent. Restore the figure, or remove the assertion from ` +
        `scripts/check-docs.mjs deliberately.`,
    );
    continue;
  }
  for (const match of found) {
    captures.forEach(({ expected, what }, i) => {
      if (match[i + 1] !== String(expected)) {
        problems.push(
          `${file} advertises "${match[0].trim()}" — the code has ${expected} for ${what}. ` +
            `If that figure is deliberately about a subset rather than the whole library, spell ` +
            `the number as a word ("three overlay components") so it does not read as a claim ` +
            `about the total.`,
        );
      }
    });
  }
}

if (problems.length) {
  console.error("Documentation disagrees with the code:\n");
  for (const p of problems) console.error(`  • ${p}`);
  console.error("");
  process.exit(1);
}

console.log(
  `Docs OK — DS v${shortVersion} (${version}), ${tokenCount} tokens · ${componentCount} components, ` +
    `${assertions} assertions.`,
);
